apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default-tracing-sampling # A descriptive name
  namespace: istio-system # Or the namespace where your applications are
spec:
  tracing:
  - providers:
    - name: jaeger # This name must match the name defined in your IstioOperator extensionProvider
    randomSamplingPercentage: 50
